### ISSUE TITLE
about "EBtimecourse"

### ISSUE THREAD

**Issue by Liulab** [ttgump/EBtimecourse#1]
Hi,
Following your instruction, I source("EBtimecourse.R"),  ran example data., and got error as follows,
Error in py_get_attr_impl(x, name, silent) :
  AttributeError: module 'tensorflow.python.util.compat' has no attribute 'v1'
I try to read the code of EBtimecourse.R, and found "tf <- tf$compat$v1" has not been defined in the function, so I tested this code independently, and got the same error.
I wondered if I missed some environment variable.
Best wishes,
Yulan Deng

**Comment by ttgump** [comment]
Did you install python tensorflow 2.0? See the tensorflow R instruction: [https://tensorflow.rstudio.com/installation/](url)

**Comment by Liulab** [comment]
Thank you for your answer,
It's solved. I changed the version of tensorflow, and it works.
Best wishes.

**Comment by ttgump** [comment]
Great 👍
