### ISSUE TITLE
could EBtimecourse apply to scRNAseq？

### ISSUE THREAD

**Issue by Liulab** [ttgump/EBtimecourse#2]
could EBtimecourse apply to scRNseq？If so，what cautious should I take？
Best wishes

**Comment by ttgump** [comment]
> could EBtimecourse apply to scRNseq？If so，what cautious should I take？
> Best wishes

Hi,
The assumption of EBtimecourse is that the data follows a normal distribution. The model is flexible and allows each gene and each segment has its own mean and variance. So the only concern is that your data should approximately follow a normal distribution. ScRNA-seq data is discrete count, direct applying to EBtimecourse may not be suitable, and normalization by library size and log transform are required. I think in the R package Seurat it has normalization and log scale functions, and python package scanpy has similar functions too.
Best,

**Comment by Liulab** [comment]
Thanks a lot. I would try it.
